# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Update Airports and Frequencies

on:
  pull_request:
    paths:
      - .github/workflows/update-ourairports.yml
      - scripts/ourairports
  schedule:
    - cron:  '0 13 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Install dependencies
        run: gem install countries
      - name: Retrieve Airports and Frequencies and save output as JSON
        run: ruby scripts/ourairports
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        if: github.event_name != 'pull_request'
        with:
          author_name: Airframes.io
          author_email: code@airframes.io
          message: "Update Airports and Frequencies"
          add: "json/*.json"
          fetch: false
        env:
          GITHUB_TOKEN: ${{ github.token }}
